name: Python Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v6

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Executar tests
        run: python -m unittest test_utils.py
